# Generated by Django 2.1.2 on 2020-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
